name: aki_calendar_date_time_picker
description: An easy date time picker from calendar and buttons
version: 0.0.2
homepage: https://github.com/AKI-YU/aki_calendar_date_time_picker

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

topics:
  - datetimepicker
  - calendar
  - calendarpicker
  - calendardatetimepicker
  