name: aki_calendar_date_time_picker
description: aki calendar datetime picker is a powerful tool for apps that need advanced date and time selection. It combines a calendar view with a time picker, making it easy for users to choose dates and times. Its user-friendly design ensures smooth navigation, and developers can customize its appearance and behavior to fit their project.
version: 0.0.4
homepage: https://github.com/AKI-YU/aki_calendar_date_time_picker

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

topics:
  - datetimepicker
  - calendar
  - calendarpicker
  - calendardatetimepicker

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

repository: https://github.com/AKI-YU/aki_calendar_date_time_picker/
      